#paths = ["/home/arturo/Code/na"]

[build]
target-dir = "./target"
#rustflags = ["-Clink-arg=-fuse-ld=lld", "-Zshare-generics"]
#rustflags = ["-Clink-arg=-fuse-ld=lld"]
#rustflags = ["-Clink-arg=-fuse-ld=mold"]
#pipelining = true

[target.x86_64-unknown-linux-gnu]
linker = "clang"
#rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold", "-Zshare-generics"]
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]
